[Interface]
# PublicKey = vRGm3eWJIbB9Q2aBUNp9HZMGErUfHdB9s+wipVlAl1E=
PrivateKey = WOthKtcRlOZn49FCIT4ItXyj/GK7zCNeSPBph+P7jkY=
Address = 10.77.0.2/24
MTU = 180
TapName = mesh0
MeshtasticConnect = serial:///dev/ttyACM0

[Peer]
PublicKey = pX7CIWM8bN39wicn34BfG/X3B/2yZzZaypP6U8ZaoiQ=
PresharedKey = GSQAJA5aYyzY2D/H+q5VHWJ/+wmsfR8Tk1iU9XkBAYk=
AllowedIPs = 10.77.0.1/32
Endpoint = !f71e3014
