[Interface]
# PublicKey = pX7CIWM8bN39wicn34BfG/X3B/2yZzZaypP6U8ZaoiQ=
PrivateKey = QJgiFWXF28U5mISfyLZN4NednUw6K8oUJ8+6wuD6pEw=
Address = 10.77.0.1/24
MTU = 180
TapName = mesh0
MeshtasticConnect = tcp://10.1.5.3:4403

[Peer]
PeerMode = symmetric
PublicKey = vRGm3eWJIbB9Q2aBUNp9HZMGErUfHdB9s+wipVlAl1E=
PresharedKey = GSQAJA5aYyzY2D/H+q5VHWJ/+wmsfR8Tk1iU9XkBAYk=
AllowedIPs = 10.77.0.2/32
Endpoint = !d45b9db8